server:
  port: 7676
spring:
  security:
    oauth2:
      client:
        registration:
          client-server-oidc:
            provider: spring
            client-id: client-server
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:7676/login/oauth2/code/{registrationId}"
            scope: openid, profile
            client-name: client-server-oidc
        provider:
          spring:
            issuer-uri: http://localhost:7373


logging.level.org.springframework.security: trace